version: '3.9'

services:
  app:
    image: sudoku-server
    container_name: sudoku-server
    ports:
      - '3000:3000'
    command: sh -c "npm install && npm run dev"
    environment:
      - MONGO_URI=mongodb://mongo:27017/sudoku
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
